version: "3"

services:
    filebrowser:
        build: ./image
        # user: "${UID}:${GID}"
        ports:
            - 8585:80
        volumes:
            - /:/srv
        restart: always
        networks:
            - behind-nginx
        container_name: filebrowser

networks:
    behind-nginx:
        external:
            name: behind-nginx-network
