version: "3"

services:
    filebrowser:
        image: filebrowser/filebrowser:s6
        # user: "${UID}:${GID}"
        ports:
            - 8070:80
        # environment:
        #     - PUID=$$(id -u)
        #     - PGID=$$(id -g)
        volumes:
            - /:/srv
            - /data/filebrowser/database:/database/
            - /data/filebrowser/config:/config/
        restart: always
        networks:
            - behind-nginx
        container_name: filebrowser

networks:
    behind-nginx:
        external:
            name: behind-nginx-network

# docker run \
#     --name filebrowser \
#     --network=behind-nginx-network \
#     --restart unless-stopped \
#     -v /:/srv \
#     -v /data/filebrowser/database:/database/ \
#     -v /data/filebrowser/config:/config/ \
#     -e PUID=$(id -u) \
#     -e PGID=$(id -g) \
#     -p 8070:80 \
#     -d \
#     filebrowser/filebrowser:s6
